// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import '../src/styles/base.css';
import '../src/styles/labels.css';
import '../src/styles/figure.css';
import '../src/styles/overlay.css';
import '../src/styles/overlay/active-quest.css';
import '../src/styles/overlay/friend-list.css';
import '../src/styles/overlay/profile.css';
import '../src/styles/overlay/skill-ledger.css';
import '../src/styles/overlay/quest-board.css';
import '../src/styles/overlay/quest-log.css';
import '../src/styles/overlay/setting.css';
import '../src/styles/overlay/feedback.css';
import '../src/styles/overlay/shop.css';
import '../src/styles/ui/badges.css';
import '../src/styles/ui/buttons.css';
import '../src/styles/ui/progress-bar.css';
import '../src/styles/ui/toast.css';
import '../src/styles/ui/confirm.css';
import '../src/styles/ui/prompt-dialog.css';
import '../src/styles/ui/tutorial-complete-modal.css';
import '../src/styles/ui/skill-activity-log.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
